"use server";
import bcrypt from 'bcryptjs'; import crypto from 'crypto'; import {redirect} from 'next/navigation'; import {revalidatePath} from 'next/cache'; import {db} from './prisma'; import {createSession,requireRoles,requireUser} from './session'; import {Role,TicketPriority,TicketStatus,ServiceType} from '@prisma/client';
export async function login(formData:FormData){const email=String(formData.get('email')||'').trim().toLowerCase(), password=String(formData.get('password')||''); const u=await db.user.findUnique({where:{email}}); if(!u||u.status!=='ACTIVE'||!(await bcrypt.compare(password,u.passwordHash))) throw new Error('بيانات الدخول غير صحيحة'); await createSession(u.id); redirect('/dashboard');}
export async function register(formData:FormData){const name=String(formData.get('name')||''),email=String(formData.get('email')||'').trim().toLowerCase(),password=String(formData.get('password')||''),confirm=String(formData.get('confirm')||''); if(password.length<10||password!==confirm)throw new Error('كلمة المرور يجب أن تكون 10 أحرف على الأقل ومتطابقة'); const exists=await db.user.findUnique({where:{email}}); if(exists)throw new Error('البريد مستخدم بالفعل'); const hash=await bcrypt.hash(password,12); await db.user.create({data:{name,email,passwordHash:hash}}); redirect('/login?registered=1');}
export async function createStaff(formData:FormData){const a=await requireRoles(['SUPER_ADMIN','ADMIN']); const role=String(formData.get('role')) as Role; const email=String(formData.get('email')).trim().toLowerCase(), name=String(formData.get('name')), pass=String(formData.get('password')); if(!['ADMIN','SUPPORT','SALES','MARKETING'].includes(role))throw new Error('Invalid role'); const hash=await bcrypt.hash(pass,12); const u=await db.user.create({data:{name,email,passwordHash:hash,role,emailVerifiedAt:new Date()}}); await db.passwordEvent.create({data:{userId:u.id,changedById:a.id,action:'INITIAL_PASSWORD_SET'}}); await db.auditLog.create({data:{userId:a.id,action:'CREATE_STAFF',entity:u.id,metadata:JSON.stringify({role})}}); revalidatePath('/admin/users');}
export async function changePassword(formData:FormData){const u=await requireUser(); const old=String(formData.get('old')),next=String(formData.get('new')),confirm=String(formData.get('confirm')); if(next.length<10||next!==confirm)throw new Error('كلمة المرور الجديدة غير صالحة'); if(!(await bcrypt.compare(old,u.passwordHash)))throw new Error('كلمة المرور الحالية غير صحيحة'); await db.user.update({where:{id:u.id},data:{passwordHash:await bcrypt.hash(next,12)}}); await db.passwordEvent.create({data:{userId:u.id,changedById:u.id,action:'PASSWORD_CHANGED'}}); await db.auditLog.create({data:{userId:u.id,action:'PASSWORD_CHANGED',entity:u.id}}); revalidatePath('/settings');}
export async function createTicket(formData:FormData){const u=await requireUser(); const t=await db.ticket.create({data:{subject:String(formData.get('subject')),message:String(formData.get('message')),priority:(String(formData.get('priority')||'MEDIUM') as TicketPriority),customerId:u.id}}); await db.ticketMessage.create({data:{ticketId:t.id,senderId:u.id,body:t.message}}); revalidatePath('/tickets');}
export async function replyTicket(formData:FormData){const u=await requireRoles(['SUPER_ADMIN','ADMIN','SUPPORT']); const id=String(formData.get('ticketId')),body=String(formData.get('body')); await db.ticketMessage.create({data:{ticketId:id,senderId:u.id,body,internal:false}}); await db.ticket.update({where:{id},data:{status:TicketStatus.IN_PROGRESS,assignedToId:u.id}}); revalidatePath('/support');}
export async function createMeeting(formData:FormData){const u=await requireRoles(['SUPER_ADMIN','ADMIN']); const starts=new Date(String(formData.get('startsAt'))), ends=new Date(String(formData.get('endsAt'))); const m=await db.meeting.create({data:{title:String(formData.get('title')),description:String(formData.get('description')||''),startsAt:starts,endsAt:ends,location:String(formData.get('location')||''),meetingUrl:String(formData.get('meetingUrl')||''),createdById:u.id}}); const ids=String(formData.get('participantIds')||'').split(',').map(x=>x.trim()).filter(Boolean); if(ids.length)await db.meetingParticipant.createMany({data:ids.map(userId=>({meetingId:m.id,userId})) ,skipDuplicates:true}); revalidatePath('/admin/meetings');}
export async function generateTestCredits(formData:FormData){const a=await requireRoles(['SUPER_ADMIN','ADMIN']); const userId=String(formData.get('userId')), amount=Math.max(0,Number(formData.get('amount')||0)); await db.user.update({where:{id:userId},data:{testCredits:{increment:amount}}}); await db.auditLog.create({data:{userId:a.id,action:'GENERATE_TEST_CREDITS',entity:userId,metadata:JSON.stringify({amount})}}); revalidatePath('/admin/users');}
export async function runHealthScan(){const a=await requireRoles(['SUPER_ADMIN','ADMIN','SUPPORT']); const checks:{name:string,ok:boolean,msg:string}[]=[]; try{await db.$queryRaw`SELECT 1`;checks.push({name:'PostgreSQL',ok:true,msg:'Database reachable'})}catch(e){checks.push({name:'PostgreSQL',ok:false,msg:'Database unreachable'})} for(const [n,fn] of [['Users',()=>db.user.count()],['Tickets',()=>db.ticket.count()],['Providers',()=>db.provider.count()],['API keys',()=>db.apiKey.count()]] as any){try{await fn();checks.push({name:n,ok:true,msg:'Query OK'})}catch{checks.push({name:n,ok:false,msg:'Query failed'})}} for(const c of checks)if(!c.ok)await db.errorEvent.create({data:{severity:'ERROR',source:'HEALTH_SCAN',message:c.msg,fingerprint:c.name}}); await db.auditLog.create({data:{userId:a.id,action:'HEALTH_SCAN',metadata:JSON.stringify(checks)}}); revalidatePath('/errors'); return checks;}
export async function repairOpenErrors(){const a=await requireRoles(['SUPER_ADMIN','ADMIN']); const errors=await db.errorEvent.findMany({where:{status:'OPEN'}}); for(const e of errors)await db.errorEvent.update({where:{id:e.id},data:{status:'RESOLVED',resolvedAt:new Date(),resolvedById:a.id}}); await db.auditLog.create({data:{userId:a.id,action:'AUTO_REPAIR',metadata:JSON.stringify({count:errors.length})}}); revalidatePath('/errors');}
export async function createApiKey(formData:FormData){const u=await requireUser(); const mode=String(formData.get('mode')||'test')==='live'?'live':'test'; const raw='otp_'+mode+'_'+crypto.randomBytes(24).toString('hex'); await db.apiKey.create({data:{userId:u.id,name:String(formData.get('name')||'Default'),mode,keyHash:crypto.createHash('sha256').update(raw).digest('hex')}}); return raw;}

export async function updateUser(formData:FormData){const a=await requireRoles(['SUPER_ADMIN','ADMIN']); const id=String(formData.get('userId')); const role=String(formData.get('role')) as Role; const status=String(formData.get('status')) as any; await db.user.update({where:{id},data:{name:String(formData.get('name')),role,status}}); await db.auditLog.create({data:{userId:a.id,action:'UPDATE_USER',entity:id,metadata:JSON.stringify({role,status})}}); revalidatePath('/admin/users');}
export async function deleteUser(formData:FormData){const a=await requireRoles(['SUPER_ADMIN']); const id=String(formData.get('userId')); const target=await db.user.findUnique({where:{id}}); if(!target||target.role==='SUPER_ADMIN')throw new Error('لا يمكن حذف Super Admin'); await db.user.delete({where:{id}}); await db.auditLog.create({data:{userId:a.id,action:'DELETE_USER',entity:id}}); revalidatePath('/admin/users');}
export async function resetUserPassword(formData:FormData){const a=await requireRoles(['SUPER_ADMIN','ADMIN']); const id=String(formData.get('userId')), next=String(formData.get('newPassword')); if(next.length<10)throw new Error('كلمة المرور يجب أن تكون 10 أحرف على الأقل'); await db.user.update({where:{id},data:{passwordHash:await bcrypt.hash(next,12)}}); await db.passwordEvent.create({data:{userId:id,changedById:a.id,action:'ADMIN_PASSWORD_RESET'}}); await db.auditLog.create({data:{userId:a.id,action:'ADMIN_PASSWORD_RESET',entity:id}}); revalidatePath('/admin/users');}
export async function supportBot(formData:FormData){const u=await requireUser(); const text=String(formData.get('text')||'').toLowerCase(); let answer='أفهم المشكلة. اختر فتح تذكرة ليقوم فريق الدعم بمتابعتها.'; if(text.includes('رصيد')||text.includes('credit'))answer='يمكنك مراجعة الرصيد والـTest Credits من لوحة العميل. إذا كان هناك خصم غير صحيح افتح تذكرة.'; else if(text.includes('otp')||text.includes('رسالة'))answer='راجع Delivery Center لمعرفة حالة الرسالة والـProvider والتكلفة. إذا كانت Failed افتح تذكرة وسيتم التصعيد.'; else if(text.includes('api'))answer='يمكن لفريق الدعم فحص API وHealth Center وسجل الطلبات. اختر تصعيد المشكلة إذا لم تُحل.'; await db.auditLog.create({data:{userId:u.id,action:'SUPPORT_BOT_MESSAGE',metadata:JSON.stringify({text,answer})}}); return answer;}
export async function createOtpTest(formData:FormData){const u=await requireUser(); const recipient=String(formData.get('recipient')); const service=String(formData.get('service')) as ServiceType; if(u.testCredits<=0)throw new Error('لا يوجد رصيد اختبار'); await db.user.update({where:{id:u.id},data:{testCredits:{decrement:1}}}); await db.otpLog.create({data:{userId:u.id,recipient,service,status:'TEST_QUEUED',provider:'Test Provider',credits:1,isTest:true}}); revalidatePath('/dashboard');}
